"""
Test Suite for Esy FARM ML Modules
===================================
Validates the following 4 core requirements:
1. Chronos-2 model (`amazon/chronos-2`) can be loaded successfully on CPU.
2. Price forecasting function executes with historical price sequence and official MSP reference.
3. Demand prediction function executes and returns expected demand per slot.
4. Smart slot recommender receives predictions and ranks slots to return an optimal recommended slot.

NOTE: All test data points used herein are strictly TEST DATA for validation purposes,
not government-issued historical datasets.
"""

import sys
import os

# Add parent directory to sys.path so ml package can be imported directly
CURRENT_DIR = os.path.dirname(os.path.abspath(__file__))
PARENT_DIR = os.path.dirname(CURRENT_DIR)
if PARENT_DIR not in sys.path:
    sys.path.insert(0, PARENT_DIR)

from ml.price_estimator import load_price_model, predict_crop_price
from ml.demand_predictor import load_demand_model, predict_slot_demand, predict_all_slots_demand
from ml.slot_recommender import recommend_procurement_slot


def test_1_load_chronos2():
    print("\n" + "=" * 60)
    print("TEST 1: Loading Pretrained Chronos-2 Model from Hugging Face")
    print("=" * 60)
    pipeline = load_price_model(model_name="amazon/chronos-2", device_map="cpu")
    assert pipeline is not None, "Pipeline failed to load."
    print("SUCCESS: amazon/chronos-2 loaded successfully on CPU.")
    return pipeline


def test_2_price_forecasting():
    print("\n" + "=" * 60)
    print("TEST 2: Price Forecasting Function Execution")
    print("=" * 60)
    # [TEST DATA] Synthetic sequence representing historical weekly price trend (INR/quintal)
    test_historical_prices = [2150.0, 2180.0, 2220.0, 2210.0, 2260.0, 2290.0]
    official_msp_benchmark = 2250.0  # Reference benchmark (e.g. MSP for Kharif season)

    result = predict_crop_price(
        crop="Ragi",
        district="Mandya",
        season="Kharif",
        historical_prices=test_historical_prices,
        msp=official_msp_benchmark,
        prediction_length=3,
        date="2026-09-13",
    )

    print(f"Crop: {result['crop']}")
    print(f"District: {result['district']}")
    print(f"Season: {result['season']}")
    print(f"Historical Prices (TEST DATA): {result['historical_prices']}")
    print(f"Official MSP Reference: INR {result['official_msp']}/quintal")
    print(f"Predicted Price Horizon (Next 3 periods): {result['predicted_prices']}")
    print(f"MSP Comparison: {result['msp_comparison']}")
    assert len(result["predicted_prices"]) == 3, "Expected 3 forecasted price points."
    print("SUCCESS: Price forecasting executed correctly.")
    return result


def test_3_demand_prediction():
    print("\n" + "=" * 60)
    print("TEST 3: Procurement Slot Demand Prediction Execution")
    print("=" * 60)
    # [TEST DATA] Synthetic sequence of historical booking volumes for this slot
    test_slot_history = [35, 42, 38, 45, 44, 49, 47]
    centre_capacity = 60

    result = predict_slot_demand(
        procurement_centre="TAPCMS Centre #104",
        crop="Paddy",
        date="2026-09-15",
        time_slot="10:00-11:00",
        historical_booking_counts=test_slot_history,
        centre_capacity=centre_capacity,
        day_of_week="Tuesday",
    )

    print(f"Slot: {result['slot']}")
    print(f"Predicted Demand: {result['predicted_demand']}")
    print(f"Centre Capacity: {result['centre_capacity']}")
    print(f"Expected Utilization: {result['expected_utilization_pct']}%")
    assert "predicted_demand" in result, "Missing predicted_demand in output."
    assert isinstance(result["predicted_demand"], int), "predicted_demand should be integer."
    print("SUCCESS: Slot demand prediction executed correctly.")
    return result


def test_4_slot_recommender():
    print("\n" + "=" * 60)
    print("TEST 4: Smart Slot Recommender Execution")
    print("=" * 60)
    available_slots = ["09:00-10:00", "10:00-11:00", "11:00-12:00", "14:00-15:00"]
    centre_capacity = 60

    # Multi-slot demand forecast generated by demand predictor
    # [TEST DATA] Historical booking curves across operating windows
    slots_history = {
        "09:00-10:00": [48, 52, 55, 50, 54, 58],
        "10:00-11:00": [30, 32, 28, 35, 31, 33],
        "11:00-12:00": [55, 58, 60, 57, 59, 61],
        "14:00-15:00": [22, 25, 20, 24, 21, 23],
    }

    predicted_demands = predict_all_slots_demand(
        procurement_centre="KAPPEC Regional Hub",
        crop="Maize",
        date="2026-09-16",
        slots_history=slots_history,
        centre_capacity=centre_capacity,
        day_of_week="Wednesday",
    )

    print("Predicted Demands Across Operating Slots:")
    for pd in predicted_demands:
        print(f"  - Slot {pd['slot']}: predicted demand = {pd['predicted_demand']} / cap {centre_capacity}")

    # Current confirmed bookings in the portal
    existing_bookings = {
        "09:00-10:00": 38,
        "10:00-11:00": 15,
        "11:00-12:00": 42,
        "14:00-15:00": 10,
    }

    recommendation = recommend_procurement_slot(
        available_slots=available_slots,
        predicted_demand=predicted_demands,
        centre_capacity=centre_capacity,
        existing_bookings=existing_bookings,
    )

    print("\nRecommendation Result:")
    print(f"  Recommended Slot: {recommendation['recommended_slot']}")
    print(f"  Predicted Demand: {recommendation['predicted_demand']}")
    print(f"  Reason: {recommendation['reason']}")
    print("\nFull Slot Ranking:")
    for rank, s in enumerate(recommendation["ranked_slots"], start=1):
        print(f"  #{rank}: {s['slot']} | Projected Congestion: {s['congestion_pct']}% | Remaining Capacity: {s['remaining_capacity']}")

    assert "recommended_slot" in recommendation, "Missing recommended_slot"
    assert "predicted_demand" in recommendation, "Missing predicted_demand"
    assert "reason" in recommendation, "Missing reason"
    print("SUCCESS: Smart slot recommender ranked slots and selected optimal slot.")
    return recommendation


def run_all_tests():
    print("=" * 60)
    print("STARTING ESY FARM ML VALIDATION SUITE")
    print("Model: amazon/chronos-2 (Hugging Face)")
    print("=" * 60)

    test_1_load_chronos2()
    test_2_price_forecasting()
    test_3_demand_prediction()
    test_4_slot_recommender()

    print("\n" + "=" * 60)
    print("ALL 4 TESTS COMPLETED SUCCESSFULLY!")
    print("=" * 60)


if __name__ == "__main__":
    run_all_tests()
