"""
Crop Price Estimator - Forecast Engine
=======================================
Predicts crop price trajectories using the pretrained `amazon/chronos-2` foundation model.

Designed for all Karnataka districts and agricultural commodities.
Maintains official MSP as an invariant reference benchmark.
"""

from typing import List, Dict, Any, Optional
import torch
import numpy as np

from .model import load_price_model


def prepare_price_tensor(historical_prices: List[float]) -> torch.Tensor:
    """
    Validates and transforms a sequence of historical crop prices into a 3-D PyTorch tensor
    with shape (n_series=1, n_variates=1, history_length) expected by Chronos-2.

    Args:
        historical_prices: List of chronological price points (INR per quintal).

    Returns:
        torch.Tensor of shape (1, 1, len(historical_prices)).
    """
    if not historical_prices or len(historical_prices) < 2:
        raise ValueError(
            "At least 2 historical price data points are required for time-series forecasting."
        )

    clean_prices = [float(p) for p in historical_prices]
    return torch.tensor([[clean_prices]], dtype=torch.float32)


def predict_crop_price(
    crop: str,
    district: str,
    season: str,
    historical_prices: List[float],
    msp: Optional[float] = None,
    prediction_length: int = 3,
    date: Optional[str] = None,
    model_name: str = "amazon/chronos-2",
) -> Dict[str, Any]:
    """
    Generates a price trend forecast for a specified crop in a given district using Chronos-2.

    Args:
        crop: Crop name (e.g., 'Ragi', 'Paddy', 'Maize', 'Bengal Gram').
        district: Target district (e.g., 'Davanagere', 'Tumakuru', 'Mandya', etc.).
        season: Agricultural season (e.g., 'Kharif', 'Rabi', 'Summer').
        historical_prices: Sequence of historical price points in INR/quintal.
        msp: Official Minimum Support Price in INR/quintal (reference benchmark only; never invented).
        prediction_length: Number of future time periods to forecast (default: 3).
        date: Reference starting date string (e.g., '2026-09-13').
        model_name: Pretrained Hugging Face model repository.

    Returns:
        Structured forecast dictionary separating model predictions from official MSP data.
    """
    pipeline = load_price_model(model_name=model_name)
    context_tensor = prepare_price_tensor(historical_prices)

    # Chronos-2 predict takes 3D tensor (n_series, n_variates, history_length)
    forecast = pipeline.predict(
        context_tensor,
        prediction_length=prediction_length,
    )

    # Forecast returns a list of tensors per series: shape [num_quantiles, n_variates, prediction_length]
    if isinstance(forecast, list) and len(forecast) > 0:
        sample_tensor = forecast[0]
    else:
        sample_tensor = forecast

    if isinstance(sample_tensor, torch.Tensor):
        arr = sample_tensor.detach().cpu().numpy()
    else:
        arr = np.array(sample_tensor)

    # Chronos-2 provides 21 quantiles where index 10 corresponds to 0.50 (median)
    # Shape: (batch=1, quantiles=21, prediction_length) -> extract 50th percentile across time steps
    if arr.ndim == 3 and arr.shape[1] == 21:
        # Exact 50th percentile quantile prediction
        median_preds = arr[0, 10, :].tolist()
    elif arr.ndim == 3:
        median_preds = np.median(arr[0], axis=0).tolist()
    elif arr.ndim == 2:
        median_preds = np.median(arr, axis=0).tolist()
    else:
        median_preds = arr.flatten()[:prediction_length].tolist()

    rounded_forecast = [round(float(val), 2) for val in median_preds]

    # Structure official MSP comparison without altering or inventing official values
    msp_comparison = None
    if msp is not None:
        latest_predicted = rounded_forecast[-1] if rounded_forecast else None
        delta = round(latest_predicted - float(msp), 2) if latest_predicted is not None else None
        msp_comparison = {
            "official_msp": float(msp),
            "latest_predicted_price": latest_predicted,
            "difference_from_msp": delta,
            "status": "above_msp" if (delta is not None and delta >= 0) else "below_msp",
        }

    return {
        "crop": crop,
        "district": district,
        "season": season,
        "date": date,
        "historical_prices": historical_prices,
        "forecast_horizon": prediction_length,
        "predicted_prices": rounded_forecast,
        "official_msp": float(msp) if msp is not None else None,
        "msp_comparison": msp_comparison,
        "model": model_name,
        "disclaimer": (
            "Model predictions are statistical forecasts generated by the pretrained amazon/chronos-2 "
            "foundation model. Chronos-2 is a general time-series model not specifically trained on agriculture. "
            "Official MSP values are provided strictly as administrative benchmarks."
        ),
    }
